- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: /jellyfin/
        description: Media streaming server
        server: my-docker
        container: jellyfin
    - Immich:
        icon: immich.png
        href: /immich/
        description: Photo & video backup
        server: my-docker
        container: immich-server

- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: /admin/
        description: Network-wide ad blocking
        server: my-docker
        container: pihole
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: /uptime/
        description: Service monitoring
        server: my-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: mainstatus
    - Pulse:
        icon: pulse.png
        href: /pulse/
        description: Proxmox & Docker monitoring
        server: my-docker
        container: pulse
    - Netdata:
        icon: netdata.png
        href: /netdata/spaces/home-server/rooms/local/overview
        description: Real-time system monitoring
        server: my-docker
        container: netdata
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: /:81/
        description: Certificate management
        server: my-docker
        container: nginx-proxy-manager
    - Portainer:
        icon: portainer.png
        href: /portainer/
        description: Docker management UI
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: http://portainer:9000
            env: 3
            key: ptr_WVfhCAoBDWVLfVKUu29bX6od/8DnyyTCJXb7MynRqiw=
    - Home Assistant:
        icon: home-assistant.png
        href: /homeassistant/
        description: Home automation
        server: my-docker
        container: homeassistant

- Productivity:
    - Nextcloud:
        icon: nextcloud.png
        href: /nextcloud/
        description: File sync & collaboration
        server: my-docker
        container: nextcloud
    - n8n:
        icon: n8n.png
        href: /n8n/
        description: Workflow automation
        server: my-docker
        container: n8n
    - Code Server:
        icon: code.png
        href: /code/
        description: VS Code in the browser
        server: my-docker
        container: code-server
    - Ghostfolio:
        icon: ghostfolio.png
        href: /ghostfolio/
        description: Wealth management & portfolio tracker
        server: my-docker
        container: ghostfolio
    - Vaultwarden:
        icon: vaultwarden.png
        href: /vaultwarden/
        description: Password manager
        server: my-docker
        container: vaultwarden
